// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9-0eQUN_qqGHWBHMWHxnZPoEwjDe1sX0',
    appId: '1:387332526056:web:3e8ce47d471e9097b71e5d',
    messagingSenderId: '387332526056',
    projectId: 'loginregister-19b98',
    authDomain: 'loginregister-19b98.firebaseapp.com',
    storageBucket: 'loginregister-19b98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9LbcQzEWsSlpoy2Cgg3WfMWJx4L6yJxI',
    appId: '1:387332526056:android:0eafcef24ee147ffb71e5d',
    messagingSenderId: '387332526056',
    projectId: 'loginregister-19b98',
    storageBucket: 'loginregister-19b98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmxFghTbsyS5DOTE5QbnsBOjYlE6cxPY8',
    appId: '1:387332526056:ios:417e670f646861e9b71e5d',
    messagingSenderId: '387332526056',
    projectId: 'loginregister-19b98',
    storageBucket: 'loginregister-19b98.appspot.com',
    iosBundleId: 'com.example.classword',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmxFghTbsyS5DOTE5QbnsBOjYlE6cxPY8',
    appId: '1:387332526056:ios:b4d3de9889281d53b71e5d',
    messagingSenderId: '387332526056',
    projectId: 'loginregister-19b98',
    storageBucket: 'loginregister-19b98.appspot.com',
    iosBundleId: 'com.example.classword.RunnerTests',
  );
}
